engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript: true
ratings:
  paths:
    - src/**/*
exclude_paths:
    - karma.conf.js
    - test/**/*
    - wwwroot/**/*
    - src/signalr-client.js
