language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install npm -g
- npm install aurelia-cli -g
- npm install
mono:
- 4.2.2
os:
- linux
branches:
  only:
  - master
  - "/^release\\/.*$/"
  - develop
script:
- "./build.sh"
env:  
  global:
    - ENCRYPTION_LABEL: "a75b2f1dfc5f"
    - COMMIT_AUTHOR_EMAIL: "aguacongas@gmail.com"
after_success:
- chmod a+x travis-deploy.sh
- ./travis-deploy.sh
