language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install npm -g
- npm install aurelia-cli -g
- npm install
mono:
- 4.2.2
os:
- linux
branches:
  only:
  - master
  - "/^release\\/.*$/"
  - develop
script:
- "./build.sh"
env:
  global:
  - COMMIT_AUTHOR_EMAIL: aguacongas@gmail.com
  - secure: of+iC6cKMms3Vo61mTFnff+v9xJxk6VsD0bd/398r3ie4IlbpKVY6KEJ3QsDLpNQrbng9991b8p3LK58mQjBGr+Mr9S4Jan7k68MLd5JJkjDn8wQEn6ENQTtjQs1PjRI8bss3zHbvb+/ZFDqg1K5O4sVTrioW3Pqz39Vi2XCbSJNXCYF5OweZmJQm4/umW+zjOf5QdNWdL8WP+s1w7incExYykRDMp6ry9nE98V7lI2sH4zM3MZOkfXUSRnP51N0Z5/kHY5/h9gHq0rFefTrK7N8AicQMSg2QylZRIBDu9OO6Qo91ap9E3bqF20xJURF3pki+pUTmPjhEg12W6NDpQr59MuGmyMYB0d/PE79Oq9d463dOyUdWS29wXf/+Ask0r5ZmNPqJMNULUcVw9BoJq4UavKWvoOySycyRDDGwovGPORo8+cEMUer7bGSNj9BQkE9BhbUkqF+6Y2KWVhGzUTTmHaTvLMqmcCnfbsUbDy+XuEJnnq6l1B98jfHD73GQvfHYNefsaoKEGfpzu4RrKWwypluxSYg0Zhl70z6YDpiYFgqpGtXPURCqF5o8JUbnDgbDm1g6wUQKaf89Cv8kb6pXJ4M/1jlk5NpUEpJzcuH+SlfrhxMDzyoa4K3lZUHNc5iU7CZLaVkZ1NaPwNc0+UwMSb4u5uPtuBuEu4X7v0=
after_success:
- chmod a+x travis-deploy.sh
- "./travis-deploy.sh"
