language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install npm -g
- npm install aurelia-cli -g
- npm install
mono:
- 4.2.2
os:
- linux
branches:
  only:
  - master
  - "/^release\\/.*$/"
  - develop
script:
- bash ./travis-build.sh
env:  
  global:
    - ENCRYPTION_LABEL: "a75b2f1dfc5f"
    - COMMIT_AUTHOR_EMAIL: "aguacongas@gmail.com"
    - secure: OXoGN29amWpeXRLhUCInMc926tNRBpdVi3zSmokL+uLKL9fFrqSX90QgeyKwAvHs+cLgOsc4rsy5qm7ml7tRryJfvPpa3CSUhFP5Jj5f153dTC5jnJ0jLdoVfupnnPpQYZSBMQmZx8FBJXBE32qG10bRkePGC6AG3q281VGoO9cJaI+iyhudUzfbGB59I5DO0FMDUdlVCTDZ7w52s85mfBQ7tGh/P2+4eSXKUeby+1xbrLaGLWSbAYzzofVuJBgcBCIi10zzh34x+gLdfCSTmMJyjLv4tD3W3ZKYEdlsMw3Fq8u2byZ6bh4c/iyML0dvAnQDD+rF4iD0gyIy/56sPOEZl2fgPWipngQjL/bTbHE5pnIAI9QVVePiK6+iqBORbJDAWUryQbDpt7n+lisGnPOGDZl4yPY+ISh/5d3hrsMj92fNyDCxJTW4TLcqIpXMaxZKbpvhD8mzaJgU0MTes3vTJ77463JcqqJh+2LCWXZO/MeePCsIpxW1wAmhkon2JxslkmLdLXo9EGNIDiU7lwfLnR/2peUBL8xPm6GFBsHQd+axPjSrMRre3oSnJr2RPiT7gQurr1MJlClv9v8fa0OPVWknC9toU6HqnefnK3UvdsE/NsEWV7+YeGq1e0XDKZ2bOcBGfHeUpMFhJADWPmALhbfh1rwdpjfWM7ROIzs=
