version: 1.0.{build}
environment:
  githubpwd:
    secure: h7zhWIG5sQBVM6loU77ClQ==
  deploy_token:
    secure: KnRXHuLNsbckLFp46G7eh+vgioe1zT7GIPPRzDyv6LD8wIMiZ9YGGrf5T8J8HVOV
install:
- choco install gitversion.portable -pre -y
- cmd: >-
    npm install npm -g

    npm install aurelia-cli -g

    npm install
before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
build_script:
- cmd: >-
    au build --env prod
artifacts:
- path: wwwroot/dist
  name: scripts
deploy:
- provider: GitHub
  description: $(GitVersion_SemVer)
  auth_token:
    secure: 3d2qqSejMw7dKAPRA3pFqQ==
  draft: true
  prerelease: false
  on:
    branch: master
- provider: GitHub
  description: $(GitVersion_SemVer)
  auth_token:
    secure: 3d2qqSejMw7dKAPRA3pFqQ==
  draft: true
  prerelease: true
  on:
    branch: /release*/
after_deploy:
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:deploy_token):x-oauth-basic@github.com`n"
- cmd: >-
    git config --global user.email "aguacongas@gmail.com"
    
    git config --global user.name "AppVeyor"
    
    git clone -q --branch=gh-pages https://github.com/aguacongas/chatle.aurelia.git deploy
    
    cd deploy
    
    copy /Y ..\wwwroot\dist\app-bundle.js scripts
    
    copy /Y ..\wwwroot\dist\vendor-bundle.js scripts
    
    git add .
    
    git commit --amend --reset-author -m "deploy %APPVEYOR_BUILD_VERSION%"
    
    git push --no-verify --force-with-lease
